/** Punto único de exportación del esquema (lo usan el cliente y drizzle-kit). */
export * from './auth.js'
export * from './audit.js'
export * from './contacts.js'
export * from './expenses.js'
export * from './company.js'
export * from './invoices.js'
export * from './invoiceSharing.js'
export * from './inbound.js'
export * from './attachments.js'
